SET client_min_messages = warning;
SELECT 'T01'; SELECT upper('aä日'), lower('AÄ日'), initcap('hello world'), reverse('日本語');
SELECT 'T02'; SELECT length('日本'), char_length('日本'), bit_length('日本'), octet_length('日本');
SELECT 'T03'; SELECT substr('日本語',2), substr('日本語',2,1), substring('日本語' from 2 for 1), left('日本語',2), right('日本語',2);
SELECT 'T04'; SELECT left('abc',-1), right('abc',-1), substr('abc',0,2), substr('abc',-1,3);
SELECT 'T05'; SELECT lpad('ab',5,'xy'), rpad('ab',5,'xy'), lpad('abcdef',3), lpad('ab',5);
SELECT 'T06'; SELECT trim('  a  '), ltrim('xxax','x'), rtrim('xxax','x'), btrim('xxaxx','x'), trim(both 'x' from 'xax');
SELECT 'T07'; SELECT position('b' in 'abc'), strpos('abc','b'), position('' in 'abc'), strpos('','a');
SELECT 'T08'; SELECT replace('aaa','aa','b'), overlay('abcdef' placing 'XY' from 2 for 3), translate('abc','ab','xy');
SELECT 'T09'; SELECT split_part('a,b,c',',',2), split_part('a,b,c',',',-1), split_part('a,b,c',',',9);
SELECT 'T10'; SELECT string_to_array('a,b',','), array_to_string(ARRAY['a','b'],'-'), string_to_table('a,b',',');
SELECT 'T11'; SELECT concat('a',NULL,'b'), concat_ws('-','a',NULL,'b'), 'a'||NULL;
SELECT 'T12'; SELECT format('%s|%I|%L', 'a','b','c'), format('%1$s%1$s','x'), format('[%10s]','ab'), format('[%-10s]','ab');
SELECT 'T13'; SELECT md5('abc'), upper(sha256('abc'::bytea)::text), length(sha512('abc'::bytea)::text);
SELECT 'T14'; SELECT 'abc' LIKE 'a%', 'abc' LIKE '%b%', 'abc' LIKE 'A%', 'abc' ILIKE 'A%', 'a%c' LIKE 'a\%c';
SELECT 'T15'; SELECT 'abc' SIMILAR TO 'a_c', 'abc' ~ '^a.c$', 'abc' ~* '^A.C$', 'abc' !~ 'z';
SELECT 'T16'; SELECT regexp_replace('abcabc','b','X'), regexp_replace('abcabc','b','X','g'), regexp_match('abc','(a)(b)');
SELECT 'T17'; SELECT regexp_split_to_array('a1b2c','[0-9]'), regexp_count('aaa','a'), regexp_substr('abc','b');
SELECT 'T18'; SELECT ascii('A'), chr(65), to_hex(255), quote_ident('a b'), quote_literal('it''s'), quote_nullable(NULL);
SELECT 'T19'; SELECT starts_with('abc','ab'), 'abc' ^@ 'ab', strpos('日本語','語');
SELECT 'T20'; SELECT repeat('ab',3), reverse(''), lpad('',3,'x'), translate('abc','','x');
SELECT 'T21'; SELECT to_char(1234.5678,'999,999.99'), to_char(1234,'0000'), to_char(-1,'999');
SELECT 'T22'; SELECT to_number('1,234.56','999,999.99'), to_date('2020-01-02','YYYY-MM-DD'), to_timestamp('2020-01-02 03:04:05','YYYY-MM-DD HH24:MI:SS');
SELECT 'T23'; SELECT encode('\x0102'::bytea,'hex'), encode('abc'::bytea,'base64'), decode('YWJj','base64');
SELECT 'T24'; SELECT convert_from('\x616263'::bytea,'UTF8'), convert_to('abc','UTF8');
SELECT 'T25'; SELECT s, upper(s), length(s), s||'!' FROM dc ORDER BY id;
