SET client_min_messages = warning;
SELECT 'T01'; SELECT count(*), count(g), sum(g), avg(g), min(g), max(g), stddev(g), variance(g) FROM dc;
SELECT 'T02'; SELECT sum(g) FILTER (WHERE g>10), count(*) FILTER (WHERE b), avg(n) FILTER (WHERE n>0) FROM dc;
SELECT 'T03'; SELECT string_agg(s,',' ORDER BY id), array_agg(id ORDER BY id DESC), json_agg(id ORDER BY id) FROM dc;
SELECT 'T04'; SELECT jsonb_agg(g ORDER BY id), jsonb_object_agg(id::text, g) FROM dc;
SELECT 'T05'; SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY g), percentile_disc(0.5) WITHIN GROUP (ORDER BY g), mode() WITHIN GROUP (ORDER BY g) FROM dc;
SELECT 'T06'; SELECT corr(id,g), covar_pop(id,g), regr_slope(id,g), regr_count(id,g) FROM dc;
SELECT 'T07'; SELECT g, count(*), grouping(g) FROM dc GROUP BY ROLLUP(g) ORDER BY g NULLS LAST, 2, 3;
SELECT 'T08'; SELECT g, id%2 h, count(*) FROM dc GROUP BY CUBE(g, id%2) ORDER BY g NULLS LAST, h NULLS LAST;
SELECT 'T09'; SELECT g, count(*) FROM dc GROUP BY GROUPING SETS ((g),()) ORDER BY g NULLS LAST, 2;
SELECT 'T10'; SELECT g, count(*) FROM dc GROUP BY g HAVING count(*) > 1 ORDER BY g;
SELECT 'T11'; SELECT id, sum(id) OVER (), sum(id) OVER (ORDER BY id), sum(id) OVER (PARTITION BY g ORDER BY id) FROM dc ORDER BY id;
SELECT 'T12'; SELECT id, row_number() OVER (ORDER BY id), rank() OVER (ORDER BY g), dense_rank() OVER (ORDER BY g), ntile(2) OVER (ORDER BY id) FROM dc ORDER BY id;
SELECT 'T13'; SELECT id, lag(id) OVER (ORDER BY id), lead(id,2,-1) OVER (ORDER BY id), first_value(id) OVER (ORDER BY id), last_value(id) OVER (ORDER BY id) FROM dc ORDER BY id;
SELECT 'T14'; SELECT id, sum(id) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), sum(id) OVER (ORDER BY id RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM dc ORDER BY id;
SELECT 'T15'; SELECT id, sum(id) OVER (ORDER BY g GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM dc ORDER BY id;
SELECT 'T16'; SELECT id, count(*) OVER (ORDER BY g RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE CURRENT ROW) FROM dc ORDER BY id;
SELECT 'T17'; SELECT count(*) FROM dc WHERE false; SELECT sum(g) FROM dc WHERE false; SELECT array_agg(g) FROM dc WHERE false;
SELECT 'T18'; SELECT avg(si), avg(bi), sum(si), sum(bi), avg(n), sum(n) FROM dc;
SELECT 'T19'; SELECT count(DISTINCT g), sum(DISTINCT g), array_agg(DISTINCT g ORDER BY g) FROM dc;
SELECT 'T20'; SELECT any_value(g) IS NOT NULL FROM dc;
