SET client_min_messages = warning;
SELECT 'T01'; SELECT j, j->'k', j->>'k', j#>'{k}', j#>>'{k}' FROM dc ORDER BY id;
SELECT 'T02'; SELECT '{"a":{"b":[1,2]}}'::JSONB #> '{a,b,1}', '{"a":{"b":[1,2]}}'::JSONB #>> '{a,b,1}';
SELECT 'T03'; SELECT '{"a":1}'::JSONB ? 'a', '{"a":1}'::JSONB ?| ARRAY['a','z'], '{"a":1}'::JSONB ?& ARRAY['a','z'];
SELECT 'T04'; SELECT '{"a":1,"b":2}'::JSONB - 'a', '[1,2,3]'::JSONB - 1, '{"a":{"b":1}}'::JSONB #- '{a,b}';
SELECT 'T05'; SELECT '{"a":1}'::JSONB || '{"b":2}'::JSONB, '[1]'::JSONB || '[2]'::JSONB;
SELECT 'T06'; SELECT jsonb_typeof('1'::JSONB), jsonb_typeof('"a"'::JSONB), jsonb_typeof('[]'::JSONB), jsonb_typeof('{}'::JSONB), jsonb_typeof('null'::JSONB);
SELECT 'T07'; SELECT jsonb_array_length('[1,2,3]'), jsonb_object_keys('{"b":1,"a":2}');
SELECT 'T08'; SELECT * FROM jsonb_each('{"b":1,"a":2}') ORDER BY 1,2;
SELECT 'T09'; SELECT * FROM jsonb_array_elements('[1,"a",null]') WITH ORDINALITY t(v,o) ORDER BY o;
SELECT 'T10'; SELECT jsonb_strip_nulls('{"a":null,"b":1}'), jsonb_pretty('{"a":1}');
SELECT 'T11'; SELECT jsonb_path_query('{"a":[1,2,3]}','$.a[*] ? (@ > 1)');
SELECT 'T12'; SELECT to_jsonb(1), to_jsonb('a'::TEXT), to_jsonb(ARRAY[1,2]), to_jsonb(NULL::INT) IS NULL;
SELECT 'T13'; SELECT jsonb_build_object('b',1,'a',2), jsonb_build_array(1,'a',NULL);
SELECT 'T14'; SELECT jsonb_set('{"a":1}','{b}','2'), jsonb_set('{"a":1}','{b}','2',false), jsonb_insert('{"a":1}','{b}','2');
SELECT 'T15'; SELECT '{"a":1}'::JSONB @> '{"a":1}', '{"a":1}'::JSONB <@ '{"a":1,"b":2}';
SELECT 'T16'; SELECT a, a[1], a[1:2], array_append(a,9), array_prepend(0,a), array_cat(a,ARRAY[7]) FROM dc WHERE a IS NOT NULL ORDER BY id;
SELECT 'T17'; SELECT array_position(ARRAY[1,2,2],2), array_positions(ARRAY[1,2,2],2), array_remove(ARRAY[1,2,2],2), array_replace(ARRAY[1,2],2,9);
SELECT 'T18'; SELECT array_dims(ARRAY[[1,2],[3,4]]), array_ndims(ARRAY[[1,2]]), array_upper(ARRAY[1,2],1), array_lower(ARRAY[1,2],1);
SELECT 'T19'; SELECT ARRAY[1,2] @> ARRAY[1], ARRAY[1] <@ ARRAY[1,2], ARRAY[1,2] && ARRAY[2,3];
SELECT 'T20'; SELECT unnest(ARRAY[1,2]) , array_agg(x) FROM unnest(ARRAY[3,4]) x;
