SET client_min_messages = warning;
SELECT 'T01'; DROP TABLE IF EXISTS ix CASCADE; CREATE TABLE ix (id INT, s TEXT, n NUMERIC, a INT[], j JSONB);
SELECT 'T02'; INSERT INTO ix SELECT g, 'row'||g, g/2.0, ARRAY[g,g+1]::INT[], ('{"k":'||g||'}')::JSONB FROM generate_series(1,50) g;
SELECT 'T03'; INSERT INTO ix VALUES (NULL,NULL,NULL,NULL,NULL),(NULL,NULL,NULL,NULL,NULL);
SELECT 'T04'; CREATE INDEX ix_id ON ix(id); SELECT count(*) FROM ix WHERE id = 7;
SELECT 'T05'; CREATE INDEX ix_expr ON ix((lower(s))); SELECT count(*) FROM ix WHERE lower(s) = 'row7';
SELECT 'T06'; CREATE INDEX ix_part ON ix(id) WHERE id > 40; SELECT count(*) FROM ix WHERE id > 45;
SELECT 'T07'; CREATE UNIQUE INDEX ix_u ON ix(id); SELECT count(*) FROM ix WHERE id IS NULL;
SELECT 'T08'; INSERT INTO ix (id) VALUES (7);
SELECT 'T09'; CREATE UNIQUE INDEX ix_unn ON ix(s) NULLS NOT DISTINCT;
SELECT 'T10'; CREATE INDEX ix_gin ON ix USING GIN (a); SELECT count(*) FROM ix WHERE a @> ARRAY[7];
SELECT 'T11'; CREATE INDEX ix_gin_j ON ix USING GIN (j); SELECT count(*) FROM ix WHERE j @> '{"k":7}';
SELECT 'T12'; CREATE INDEX ix_multi ON ix(id, s); SELECT count(*) FROM ix WHERE id = 7 AND s = 'row7';
SELECT 'T13'; CREATE INDEX ix_desc ON ix(id DESC NULLS FIRST); SELECT id FROM ix ORDER BY id DESC NULLS FIRST LIMIT 3;
SELECT 'T14'; SELECT count(*) FROM ix WHERE id BETWEEN 10 AND 20;
SELECT 'T15'; SELECT count(*) FROM ix WHERE s LIKE 'row1%';
SELECT 'T16'; DROP INDEX ix_id; SELECT count(*) FROM ix WHERE id = 7;
SELECT 'T17'; REINDEX TABLE ix; SELECT count(*) FROM ix;
SELECT 'T18'; SELECT indexname FROM pg_indexes WHERE tablename='ix' ORDER BY 1;
