SET client_min_messages = warning;
SELECT 'T01'; DROP DOMAIN IF EXISTS pos CASCADE; CREATE DOMAIN pos AS INT CHECK (VALUE > 0);
SELECT 1::pos, 'ok';
SELECT 'T02'; SELECT (-1)::pos;
SELECT 'T03'; DROP TYPE IF EXISTS mood CASCADE; CREATE TYPE mood AS ENUM ('sad','ok','happy');
SELECT 'ok'::mood, 'happy'::mood > 'sad'::mood, enum_range(NULL::mood);
SELECT 'T04'; SELECT 'nope'::mood;
SELECT 'T05'; DROP TABLE IF EXISTS em; CREATE TABLE em (m mood); INSERT INTO em VALUES ('happy'),('sad'),('ok');
SELECT m FROM em ORDER BY m;
SELECT 'T06'; DROP TYPE IF EXISTS pt CASCADE; CREATE TYPE pt AS (x INT, y TEXT);
SELECT ROW(1,'a')::pt, (ROW(1,'a')::pt).x, ((1,'a')::pt).y;
SELECT 'T07'; SELECT int4range(1,5), int4range(1,5) @> 3, int4range(1,5) * int4range(3,9), upper(int4range(1,5));
SELECT 'T08'; SELECT '[1,5)'::int4range = int4range(1,5), isempty(int4range(1,1)), lower_inf('(,5)'::int4range);
SELECT 'T09'; SELECT int4multirange(int4range(1,3), int4range(5,7));
SELECT 'T10'; SELECT numrange(1.0,2.0) @> 1.5, daterange('2020-01-01','2020-02-01') @> DATE '2020-01-15';
SELECT 'T11'; SELECT tsrange(TIMESTAMP '2020-01-01', TIMESTAMP '2020-02-01') && tsrange(TIMESTAMP '2020-01-15', TIMESTAMP '2020-03-01');
SELECT 'T12'; SELECT enum_first(NULL::mood), enum_last(NULL::mood);
SELECT 'T13'; SELECT pg_typeof('ok'::mood), pg_typeof(1::pos), pg_typeof(ROW(1,'a')::pt), pg_typeof(int4range(1,2));
SELECT 'T14'; DROP TABLE IF EXISTS cx; CREATE TABLE cx (p pt); INSERT INTO cx VALUES (ROW(1,'a')); SELECT (p).x, (p).y FROM cx;
SELECT 'T15'; SELECT to_json(ROW(1,'a')::pt), row_to_json(ROW(1,'a')::pt);
