SET client_min_messages = warning;
SELECT 'T01'; DROP TABLE IF EXISTS cp; CREATE TABLE cp (id INT, s TEXT);
SELECT 'T02'; COPY cp (id,s) FROM STDIN WITH (FORMAT csv);
1,a
2,b
\.
SELECT count(*) FROM cp;
SELECT 'T03'; COPY (SELECT id,s FROM cp ORDER BY id) TO STDOUT WITH (FORMAT csv);
SELECT 'T04'; PREPARE p1 (INT) AS SELECT id FROM cp WHERE id = $1;
EXECUTE p1(1); EXECUTE p1(2); DEALLOCATE p1;
SELECT 'T05'; PREPARE p2 AS SELECT count(*) FROM cp; EXECUTE p2; DEALLOCATE ALL;
SELECT 'T06'; BEGIN; DECLARE c1 CURSOR FOR SELECT id FROM cp ORDER BY id;
FETCH 1 FROM c1; FETCH ALL FROM c1; CLOSE c1; COMMIT;
SELECT 'T07'; BEGIN; DECLARE c2 SCROLL CURSOR FOR SELECT id FROM cp ORDER BY id;
FETCH LAST FROM c2; FETCH PRIOR FROM c2; CLOSE c2; COMMIT;
SELECT 'T08'; DO $$ BEGIN RAISE NOTICE 'x'; END $$;
SELECT 'T09'; SELECT * FROM cp ORDER BY id;
