SET client_min_messages = warning;
SELECT 'T01'; DROP TABLE IF EXISTS ac CASCADE; CREATE TABLE ac (id INT, owner TEXT, s TEXT);
INSERT INTO ac VALUES (1,'u1','alpha beta'),(2,'u2','gamma delta'),(3,'u1','beta gamma');
SELECT 'T02'; ALTER TABLE ac ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_own ON ac USING (owner = current_user);
SELECT count(*) FROM ac;
SELECT 'T03'; ALTER TABLE ac FORCE ROW LEVEL SECURITY; SELECT count(*) FROM ac;
SELECT 'T04'; ALTER TABLE ac NO FORCE ROW LEVEL SECURITY; DROP POLICY p_own ON ac; ALTER TABLE ac DISABLE ROW LEVEL SECURITY; SELECT count(*) FROM ac;
SELECT 'T05'; GRANT SELECT ON ac TO PUBLIC; REVOKE SELECT ON ac FROM PUBLIC; SELECT 'acl-ok';
SELECT 'T06'; SELECT to_tsvector('english','the quick brown fox');
SELECT 'T07'; SELECT to_tsquery('english','quick & fox'), plainto_tsquery('english','quick fox');
SELECT 'T08'; SELECT to_tsvector('english','the quick brown fox') @@ to_tsquery('english','quick & fox');
SELECT 'T09'; SELECT ts_rank(to_tsvector('english','a b c'), to_tsquery('english','b')) > 0;
SELECT 'T10'; SELECT ts_headline('english','the quick brown fox', to_tsquery('english','quick'));
SELECT 'T11'; SELECT phraseto_tsquery('english','quick brown'), websearch_to_tsquery('english','quick OR brown');
SELECT 'T12'; SELECT s FROM ac WHERE to_tsvector('english',s) @@ to_tsquery('english','beta') ORDER BY id;
SELECT 'T13'; SELECT setweight(to_tsvector('english','a'),'A'), numnode(to_tsquery('english','a&b')), strip(to_tsvector('english','a b'));
SELECT 'T14'; SELECT ts_debug('english','cats') IS NOT NULL;
SELECT 'T15'; SELECT unnest(tsvector_to_array(to_tsvector('english','a b'))) ORDER BY 1;
