SET client_min_messages = warning;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
SELECT 'T01'; SELECT similarity('cat','hat'), similarity('word','two words'), similarity('a','a'), similarity('','a');
SELECT 'T02'; SELECT show_trgm('hi'), show_trgm('foo bar'), show_trgm('don''t'), show_trgm('a-b');
SELECT 'T03'; SELECT show_trgm('日本語'), show_trgm('héllo'), show_trgm('Wörter zwei'), show_trgm('한국어');
SELECT 'T04'; SELECT similarity('日本語','日本'), similarity('café','cafe'), similarity('über','uber'), similarity('héllo','hello');
SELECT 'T05'; SELECT word_similarity('word','two words'), word_similarity('cat','hat cat'), word_similarity('abcd','ab xcd'), word_similarity('ab','xaybzb');
SELECT 'T06'; SELECT strict_word_similarity('word','two words'), strict_word_similarity('sql','structured query language'), strict_word_similarity('x','xxxxx'), strict_word_similarity('abcde','abzde');
SELECT 'T07'; SELECT 'x' % 'y', 'cat' % 'cat', 'cat' % 'cot', 'word' % 'two words';
SELECT 'T08'; SELECT 'cat' <-> 'hat', 'cat' <-> 'cat', 'word' <-> 'two words';
SELECT 'T09'; SELECT 'cat' <% 'hat cat', 'hat cat' <% 'cat', 'cat' %> 'hat cat', 'hat cat' %> 'cat';
SELECT 'T10'; SELECT 'cat' <<% 'hat cat', 'cat' %>> 'hat cat', 'word' <<% 'two words', 'word' %>> 'two words';
SELECT 'T11'; SELECT 'cat' <<-> 'hat cat', 'hat cat' <<-> 'cat', 'cat' <->> 'hat cat', 'hat cat' <->> 'cat';
SELECT 'T12'; SELECT 'cat' <<<-> 'hat cat', 'cat' <->>> 'hat cat', 'word' <<<-> 'two words', 'word' <->>> 'two words';
SELECT 'T13'; SELECT show_limit(), set_limit(0.7), show_limit(), 'cat' % 'cot';
SELECT 'T14'; SELECT set_limit(0.3), show_limit();
SELECT 'T15'; SHOW pg_trgm.similarity_threshold;
SELECT 'T16'; SET pg_trgm.similarity_threshold = 0.9; SELECT show_limit(), 'cat' % 'cat';
SELECT 'T17'; RESET pg_trgm.similarity_threshold; SELECT show_limit();
SELECT 'T18'; SELECT similarity_op('cat','cat'), similarity_dist('cat','hat'), word_similarity_op('cat','hat cat'), word_similarity_commutator_op('cat','hat cat');
SELECT 'T19'; SELECT word_similarity_dist_op('cat','hat cat'), word_similarity_dist_commutator_op('cat','hat cat'), strict_word_similarity_op('cat','hat cat'), strict_word_similarity_dist_op('cat','hat cat');
SELECT 'T20'; SELECT strict_word_similarity_commutator_op('cat','hat cat'), strict_word_similarity_dist_commutator_op('cat','hat cat');
SELECT 'T21'; SELECT similarity(NULL,'a'), show_trgm(NULL), word_similarity('a',NULL), NULL % 'a';
SELECT 'T22'; DROP TABLE IF EXISTS trgc; CREATE TABLE trgc(id int, t text);
SELECT 'T23'; INSERT INTO trgc SELECT g, 'pad'||g||' foo-bar tail' FROM generate_series(1,600) g;
SELECT 'T24'; INSERT INTO trgc SELECT 9000+g, 'jp'||g||' 日本語テスト' FROM generate_series(1,60) g;
SELECT 'T25'; SELECT count(*) FROM trgc WHERE t LIKE '%foo-bar%';
SELECT 'T26'; SELECT count(*) FROM trgc WHERE t LIKE '%日本語%';
SELECT 'T27'; CREATE INDEX trgc_i ON trgc USING gin (t gin_trgm_ops);
SELECT 'T28'; SELECT count(*) FROM trgc WHERE t LIKE '%foo-bar%';
SELECT 'T29'; SELECT count(*) FROM trgc WHERE t LIKE '%日本語%';
SELECT 'T30'; SELECT count(*) FROM trgc WHERE t LIKE '%foo%';
SELECT 'T31'; SELECT count(*) FROM trgc WHERE t LIKE 'pad1 %';
SELECT 'T32'; SELECT count(*) FROM trgc WHERE t LIKE '%zzzz%';
SELECT 'T33'; SELECT count(*) FROM trgc WHERE t LIKE '%テスト';
SELECT 'T34'; SELECT id FROM trgc WHERE t % 'pad7 foo-bar tail' ORDER BY id LIMIT 3;
SELECT 'T35'; DROP TABLE trgc;
SELECT 'T36'; SELECT 5 % 2, 5.5 % 2, (-5) % 3, 5 % -3;
SELECT 'T37'; SELECT 1 % 0;
SELECT 'T38'; SELECT 1 <-> 2;
SELECT 'T39'; SELECT set_limit('x');
SELECT 'T40'; SELECT similarity('a');
