#!/usr/bin/env bash
# 差分 runner —— 见 RUNNER.md 的三条归一化
set -uo pipefail
export PATH=/Applications/OrbStack.app/Contents/MacOS/xbin:$PATH
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SPG_PORT="${SPG_PORT:-26000}"

# v7.39 (round 666) — start our own server when nothing is serving, so the
# gate protocol can run this unattended. `xtests/dump_compat/run.sh` has done
# this since it was written; this corpus was the one gate that still assumed
# a human had a server up, which is a large part of why it stayed outside
# `scripts/gate.sh` and outside version control.
# v7.39 (round 667) — ALWAYS start our own, and take the port from whoever
# has it.
#
# The first version reused any server already listening, which is how this
# gate's first real red was a false one: a probe server left running from
# before a fix was still on the port, so the gate judged a binary that was
# two commits stale and reported a deviation that no longer existed. A gate
# that silently grades an unknown build is worse than no gate — it was
# exactly the hazard the cleanup comment below already warned about, just
# arriving from the other side.
#
# SPG_REUSE=1 opts back into reusing a running server, for hand-driving
# against one you started deliberately.
OWN_SERVER=""
if [ "${SPG_REUSE:-0}" = 1 ] && (exec 3<>/dev/tcp/127.0.0.1/"$SPG_PORT") 2>/dev/null; then
  :
else
  lsof -ti :"$SPG_PORT" 2>/dev/null | xargs kill -9 2>/dev/null || true
  (cd "$ROOT" && cargo build --release --bin spg-server -q)
  SPG_DATA_DIR="$(mktemp -d)"
  export SPG_DATA_DIR
  SPG_PG_ADDR=0.0.0.0:"$SPG_PORT" "$ROOT/target/release/spg-server" 127.0.0.1:0 \
      >/tmp/spg-diffcorpus.log 2>&1 &
  OWN_SERVER=$!
  for _ in $(seq 1 40); do
    (exec 3<>/dev/tcp/127.0.0.1/"$SPG_PORT") 2>/dev/null && break
    sleep 0.5
  done
fi
# Kill by port as well as by pid: measured, the pid we backgrounded is not
# always what ends up holding the listener, and a survivor makes the NEXT run
# skip its own start and silently reuse a server with the previous run's
# state — which is the reproducibility bug this round exists to remove.
cleanup() {
  [ -n "$OWN_SERVER" ] || return 0
  kill "$OWN_SERVER" 2>/dev/null || true
  for _ in 1 2 3 4 5 6; do
    lsof -ti :"$SPG_PORT" >/dev/null 2>&1 || return 0
    sleep 0.5
  done
  lsof -ti :"$SPG_PORT" | xargs kill -9 2>/dev/null || true
}
trap cleanup EXIT

OUT="$HERE/out"; mkdir -p "$OUT"
norm() { sed -E 's/^psql:[^:]*:[0-9]+: //; /^LINE [0-9]+:/d; /^ *\^ *$/d; /^HINT:/d; /^DETAIL:/d; /^CONTEXT:/d; /^LOCATION:/d; /^(SCHEMA|TABLE|COLUMN|CONSTRAINT|DATATYPE) NAME:/d; /^LOCATION:/d; /^STATEMENT:/d'; }
# v7.39 (round 621) — stdbuf -o0. psql block-buffers stdout when it is not a
# tty while stderr stays unbuffered, so an ERROR could land BEFORE or AFTER the
# marker line of its own statement, run to run.
SPG() { docker exec -i -e PGSSLMODE=disable spg-bench-postgres stdbuf -o0 -e0 psql -h host.docker.internal -p "$SPG_PORT" -U postgres -d postgres -tA -q -v ON_ERROR_STOP=0 -c "\\pset null '<NULL>'" -f -; }
PGG() { docker exec -i -e PGPASSWORD=bench spg-bench-postgres stdbuf -o0 -e0 psql -h host.docker.internal -p 25432 -U bench -d bench -tA -q -v ON_ERROR_STOP=0 -c "\\pset null '<NULL>'" -f -; }

# v7.39 (round 621) — RESET BOTH SIDES first.
#
# Without it this runner was not reproducible: the same binary run three times
# gave three different results, one file swinging from 13 differing lines to
# 41. Both engines accumulate the corpus's own objects across runs, and a stale
# relation changes what the next run's DDL does — so the instrument A2 is
# judged on could both invent findings and hide them.
#
# PG drops and recreates its schema. SPG refuses that (public is built-in), so
# its relations are enumerated and the DROP statements generated by a query,
# then fed back in — not a DO block, which SPG does not parse here.
#
# pg_class, not information_schema.tables: the latter lists neither a
# PARTITIONED table nor a sequence nor a materialised view, and those are
# exactly what file 13 creates.
#
# Restarting the SPG server would also reset it, but starting a daemon from
# inside a script that is normally at the head of a pipe hangs the pipe: the
# server inherits the descriptors and the reader never sees EOF.
#
# NO_RESET=1 skips it, for running one file against state left on purpose.
if [ "${NO_RESET:-0}" != 1 ]; then
  PGG <<<'DROP SCHEMA public CASCADE; CREATE SCHEMA public;' >/dev/null 2>&1
  # v7.39 (round 647) — and the state that is NOT in a schema.
  #
  # `DROP SCHEMA public CASCADE` takes tables, types and functions with
  # it, which is why an enum or a composite left by a probe never
  # survived a run. A PUBLICATION is not schema-scoped, so it did: round
  # 642 found `CREATE PUBLICATION p543 FOR ALL TABLES`, left by a
  # round-543 test, still in place. Under `wal_level = replica` it makes
  # PG refuse every UPDATE and DELETE on a table without a replica
  # identity — so the corpus had been comparing SPG's real answers
  # against PG's refusals, and reported the same wrong baseline every
  # round for a hundred rounds. Reproducible is not the same as correct.
  PGG <<'GEN_PUB' 2>/dev/null | PGG >/dev/null 2>&1
SELECT 'DROP PUBLICATION IF EXISTS ' || quote_ident(pubname) || ';' FROM pg_publication;
GEN_PUB
  # Twice: a CASCADE can take a relation the first pass had already listed.
  for _pass in 1 2; do
    SPG <<'GEN_SQL' 2>/dev/null | SPG >/dev/null 2>&1
SELECT CASE relkind
         WHEN 'v' THEN 'DROP VIEW IF EXISTS '
         WHEN 'm' THEN 'DROP MATERIALIZED VIEW IF EXISTS '
         WHEN 'S' THEN 'DROP SEQUENCE IF EXISTS '
         ELSE 'DROP TABLE IF EXISTS '
       END || quote_ident(relname) || ' CASCADE;'
FROM pg_class
WHERE relnamespace = 2200 AND relkind IN ('r','p','v','m','S')
ORDER BY CASE relkind WHEN 'm' THEN 0 WHEN 'v' THEN 1 ELSE 2 END;
GEN_SQL
  done
fi

# v7.39 (round 666) — THE TWO STREAMS ARE COMPARED SEPARATELY.
#
# They used to be merged with `2>&1` and diffed as one file, which made the
# instrument non-reproducible in a way that looked like a finding. Measured:
# three consecutive runs of the same binary reported 6, 8 and 12 differing
# lines for `14-errors-sqlstate` while every other file held still. The extra
# lines were never semantic — an ERROR landing before its own marker instead
# of after, and once a marker written through mid-line (`psql:T16` followed by
# `<stdin>:16: ERROR:`).
#
# `stdbuf -o0 -e0` was already in place and does not fix it: the race is two
# file descriptors writing one pipe, not buffering. Separating them removes
# the race by construction — ordering within a single stream is deterministic.
#
# The stderr normaliser KEEPS `<stdin>:N:`. Merged output could rely on
# position to say which statement failed; separated, the line number is what
# carries that, and a failure moving to a different statement is a real
# difference worth seeing.
norm_err() { sed -E '/^LINE [0-9]+:/d; /^ *\^ *$/d; /^HINT:/d; /^DETAIL:/d; /^CONTEXT:/d; /^LOCATION:/d; /^(SCHEMA|TABLE|COLUMN|CONSTRAINT|DATATYPE) NAME:/d; /^STATEMENT:/d; s/^psql:[^:]*:/<stdin>:/'; }

# `--rebaseline` is a mode, not a file — strip it before the file list is
# built, or it is treated as one and the baseline records a bogus entry.
REBASE=0
args=()
for a in "$@"; do
  if [ "$a" = "--rebaseline" ]; then REBASE=1; else args+=("$a"); fi
done
set -- ${args[@]+"${args[@]}"}

: > "$OUT/actual.tsv"
files=("$@"); [ ${#files[@]} -eq 0 ] && files=("$HERE"/[0-9]*.sql)

# v7.37 (round 1007) — prove both legs answer before scoring anything.
#
# The scoring below diffs stdout AND stderr, so two legs that fail the SAME
# way score zero differences and print IDENTICAL. That is what happened the
# first time `gate.sh --full` reached here after a reboot: the psql container
# was down, every file produced an empty stdout and the byte-identical error
# `container ... is not running`, and the corpus reported every one of its
# twenty categories IDENTICAL — a jump from the baseline's 29 differing lines
# to zero, which reads exactly like a sweeping improvement.
#
# The next step after such a run is `--rebaseline`, which would have written
# all-zeros over the recorded 29 and left this gate unable to fail again.
#
# So: ask each leg for a row before trusting anything it says.
probe_leg() { # $1=name $2=fn
  local got
  got="$(printf 'SELECT 1;\n' | "$2" 2>/dev/null | tr -d '[:space:]')"
  if [ "$got" != "1" ]; then
    echo "diffcorpus: the $1 leg answered '${got:-<nothing>}' to SELECT 1 — it is not up." >&2
    echo "            Scoring now would compare two broken legs and call them identical." >&2
    return 1
  fi
}
probe_leg SPG SPG || exit 2
probe_leg PG18 PGG || exit 2

rc=0
for f in "${files[@]}"; do
  n="$(basename "$f" .sql)"
  SPG < "$f" > "$OUT/$n.spg.raw" 2> "$OUT/$n.spg.eraw"
  PGG < "$f" > "$OUT/$n.pg.raw"  2> "$OUT/$n.pg.eraw"
  for side in spg pg; do
    norm     < "$OUT/$n.$side.raw"  > "$OUT/$n.$side"
    norm_err < "$OUT/$n.$side.eraw" > "$OUT/$n.$side.err"
  done
  d_out=0; d_err=0
  diff -u "$OUT/$n.pg"     "$OUT/$n.spg"     > "$OUT/$n.diff"     2>&1 || d_out=$(grep -cE '^[+-][^+-]' "$OUT/$n.diff")
  diff -u "$OUT/$n.pg.err" "$OUT/$n.spg.err" > "$OUT/$n.diff.err" 2>&1 || d_err=$(grep -cE '^[+-][^+-]' "$OUT/$n.diff.err")
  tot=$((d_out + d_err))
  printf '%s\t%s\n' "$n" "$tot" >> "$OUT/actual.tsv"
  if [ "$tot" -eq 0 ]; then
    printf '%-28s IDENTICAL\n' "$n"
  else
    printf '%-28s %s 行差异 (rows %s / errors %s)\n' "$n" "$tot" "$d_out" "$d_err"
  fi
done

# v7.39 (round 666) — THE GATE IS THE BASELINE, NOT THE COUNT.
#
# This used to exit 1 whenever any file differed, which is every run: the
# baseline is 39 differing lines, not 0. A status that is always 1 gates
# nothing, so the number was read by a human instead — the same shape
# `xtests/dump_compat/run.sh` carries a comment about having outgrown in
# round 13, and the same shape that let a stale sqllogictest assertion ride
# through three green gate runs (round 664).
#
# Now: compare per file against `baseline.tsv` and fail only on deviation.
# `--rebaseline` records the current state, and is meant to be a deliberate
# act with the reason in the commit message.
BASE="$HERE/baseline.tsv"
if [ "$REBASE" = 1 ] || [ "${REBASELINE:-0}" = 1 ]; then
  sort "$OUT/actual.tsv" > "$BASE"
  echo "rebaselined -> $BASE"
  exit 0
fi
if [ ! -f "$BASE" ]; then
  echo "no baseline.tsv; run with --rebaseline to record one" >&2
  exit 2
fi
# v7.38.25 — say WHICH PostgreSQL the verdict is against.
#
# The oracle image is the rolling `postgres:18` tag, so `docker pull`
# moves it: it went 18.4 -> 18.6 under a running project without a
# single line of output anywhere changing. "matches baseline" is a claim
# about a comparison, and a comparison has two sides; naming only one of
# them lets the other move unwitnessed. A baseline recorded against one
# minor and checked against another is still a fair check -- this run
# found the 23 lines unchanged across that move -- but the reader has to
# be told, not left to assume.
ORACLE_VERSION="$(printf 'SELECT version();' | PGG 2>/dev/null | head -1)"
[ -n "$ORACLE_VERSION" ] || ORACLE_VERSION="(the oracle did not answer SELECT version())"
echo "oracle: $ORACLE_VERSION"

if diff -u "$BASE" <(sort "$OUT/actual.tsv") > "$OUT/baseline.diff" 2>&1; then
  echo "CORPUS OK — matches baseline ($(awk -F'\t' '{s+=$2} END{print s}' "$BASE") lines)"
  exit 0
fi
echo "CORPUS DEVIATES from baseline:"
grep -E '^[+-][^+-]' "$OUT/baseline.diff"
exit 1
