//! v7.39 — what level does a session get when it does not ask for one.
//!
//! The answer used to be the constant `ReadCommitted`, written out at
//! four separate sites, and it was wrong twice over.
//!
//! `SET default_transaction_isolation` did nothing. SPG accepted it and
//! read it back, so a connection pool or ORM that sets it at connect
//! time — a very ordinary thing to do — was told it had the level it
//! asked for while every transaction still ran read committed. The
//! engine HAS repeatable read; the setting simply never reached it.
//! Reporting a guarantee the session does not hold is the worst shape
//! this defect can take, because the client's only reason for asking is
//! to decide what it may assume.
//!
//! And the MySQL dialect inherited PG's default. MySQL 9.7.2 defaults to
//! REPEATABLE READ (measured: a fresh connection answers
//! `REPEATABLE-READ`), so a MySQL application relying on its own
//! engine's default was quietly given a weaker one.
//!
//! These pin the REPORT. The behaviour — that the level reaches the MVCC
//! snapshot — needs two sessions and is pinned by
//! `xtests/isolation/08`, `09` (its negative control) and `10`, whose
//! expectations were generated by running the same specs against
//! PostgreSQL 18.6.

use spg_engine::{Engine, QueryResult};
use spg_storage::Value;

fn row_text(e: &mut Engine, sql: &str) -> String {
    match e.execute(sql).unwrap_or_else(|err| panic!("{sql}: {err}")) {
        QueryResult::Rows { rows, .. } => rows
            .first()
            .map(|r| {
                r.values
                    .iter()
                    .map(|v| match v {
                        Value::Text(t) => t.to_string(),
                        other => format!("{other:?}"),
                    })
                    .collect::<Vec<_>>()
                    .join(" ")
            })
            .unwrap_or_default(),
        other => panic!("{sql}: expected rows, got {other:?}"),
    }
}

/// Measured on PG 18.6 and MySQL 9.7.2 respectively. Two engines, two
/// defaults, one SPG — which is the whole point of the dialect.
#[test]
fn a_fresh_session_defaults_to_the_level_its_dialect_defaults_to() {
    let mut pg = Engine::new();
    assert_eq!(
        row_text(&mut pg, "SHOW transaction_isolation"),
        "read committed",
        "PG 18.6 answers `read committed` on a fresh connection"
    );

    let mut my = Engine::new();
    // `SET sql_mode` is the door into MySQL semantics; ask the session,
    // do not parse the script.
    my.execute("SET sql_mode='STRICT_TRANS_TABLES'").unwrap();
    let show = row_text(&mut my, "SHOW VARIABLES LIKE 'transaction_isolation'");
    let at = row_text(&mut my, "SELECT @@transaction_isolation");
    assert!(
        show.contains("REPEATABLE-READ"),
        "MySQL 9.7.2 answers REPEATABLE-READ on a fresh connection, SHOW said {show:?}"
    );
    assert_eq!(at, "REPEATABLE-READ", "@@transaction_isolation");
}

/// The setting has to reach the transaction, and the transaction has to
/// give it back at the end. Measured on PG 18.6: baseline
/// `read committed`, then `repeatable read` inside the block AND after
/// it, because the default is what a session returns to.
#[test]
fn the_default_transaction_isolation_setting_governs_the_next_transaction() {
    let mut e = Engine::new();
    assert_eq!(
        row_text(&mut e, "SHOW transaction_isolation"),
        "read committed"
    );

    e.execute("SET default_transaction_isolation = 'repeatable read'")
        .unwrap();
    assert_eq!(
        row_text(&mut e, "SHOW transaction_isolation"),
        "repeatable read",
        "outside a transaction PG reports the default itself"
    );

    e.execute("BEGIN").unwrap();
    assert_eq!(
        row_text(&mut e, "SHOW transaction_isolation"),
        "repeatable read",
        "a transaction that names no level takes the default"
    );
    e.execute("COMMIT").unwrap();

    // Ending a transaction returns to the default, not to a constant.
    assert_eq!(
        row_text(&mut e, "SELECT current_setting('transaction_isolation')"),
        "repeatable read"
    );
}

/// An explicit level still wins over the default, and it is scoped to
/// the block — PG reverts at COMMIT.
#[test]
fn an_explicit_level_outranks_the_default_and_ends_with_the_block() {
    let mut e = Engine::new();
    e.execute("SET default_transaction_isolation = 'repeatable read'")
        .unwrap();
    e.execute("BEGIN ISOLATION LEVEL SERIALIZABLE").unwrap();
    assert_eq!(
        row_text(&mut e, "SHOW transaction_isolation"),
        "serializable"
    );
    e.execute("COMMIT").unwrap();
    assert_eq!(
        row_text(&mut e, "SHOW transaction_isolation"),
        "repeatable read",
        "the block's level ends with the block; the default is what remains"
    );
}
