//! v7.39 (round 531) — `CREATE TABLE … (LIKE <table> …)`.
//!
//! Round 530 measured this as a plain syntax error. It is the standard
//! way to declare a table shaped like another one, and migration and
//! partitioning tools emit it.
//!
//! What each spelling carries is a PG18 reading, and the bare form is
//! narrower than it looks: it copies names, types and NOT NULL and
//! nothing else, so a copied generated column becomes a plain one, a
//! copied identity column loses its identity, and a copied CHECK is
//! simply absent.
//!
//!     CREATE TABLE k (LIKE t)                     names, types, NOT NULL
//!     … INCLUDING DEFAULTS                        + column defaults
//!     … INCLUDING CONSTRAINTS                     + CHECKs
//!     … INCLUDING GENERATED / IDENTITY            + those
//!     … INCLUDING ALL                             all of the above
//!
//! The source's shape lives in the catalog, so the parser records the
//! clause and the engine expands it — at the position it was written,
//! since PG keeps the written order.

use spg_engine::{Engine, QueryResult};

fn engine() -> Engine {
    let mut e = Engine::new();
    e.execute(
        "CREATE TABLE src (id INT PRIMARY KEY, a TEXT NOT NULL DEFAULT 'dd', \
         b INT CHECK (b > 0))",
    )
    .unwrap();
    e
}

fn rows(e: &mut Engine, sql: &str) -> Vec<String> {
    match e.execute(sql).unwrap_or_else(|err| panic!("{sql}: {err}")) {
        QueryResult::Rows { rows, .. } => rows
            .iter()
            .map(|r| {
                r.values
                    .iter()
                    .map(spg_engine::eval::value_to_text)
                    .collect::<Vec<_>>()
                    .join("|")
            })
            .collect(),
        other => panic!("{sql}: {other:?}"),
    }
}

fn cols(e: &mut Engine, t: &str) -> Vec<String> {
    rows(
        e,
        &format!(
            "SELECT column_name FROM information_schema.columns \
             WHERE table_name = '{t}' ORDER BY ordinal_position"
        ),
    )
}

/// The bare form: names, types, NOT NULL.
#[test]
fn round531_bare_like_copies_columns_and_not_null() {
    let mut e = engine();
    e.execute("CREATE TABLE k1 (LIKE src)").unwrap();
    assert_eq!(cols(&mut e, "k1"), vec!["id", "a", "b"]);
    assert_eq!(
        rows(
            &mut e,
            "SELECT column_name FROM information_schema.columns \
             WHERE table_name = 'k1' AND is_nullable = 'NO' ORDER BY ordinal_position"
        ),
        vec!["id", "a"]
    );
    // And nothing else: no default, and the CHECK did not come along.
    assert_eq!(
        rows(
            &mut e,
            "SELECT count(*) FROM information_schema.columns \
             WHERE table_name = 'k1' AND column_default IS NOT NULL"
        ),
        vec!["0"]
    );
    e.execute("INSERT INTO k1 VALUES (1, 'x', -5)").unwrap();
    assert_eq!(rows(&mut e, "SELECT b FROM k1"), vec!["-5"]);
}

/// `INCLUDING DEFAULTS` brings the defaults and only those.
#[test]
fn round531_including_defaults() {
    let mut e = engine();
    e.execute("CREATE TABLE k2 (LIKE src INCLUDING DEFAULTS)")
        .unwrap();
    assert_eq!(
        rows(
            &mut e,
            "SELECT column_name FROM information_schema.columns \
             WHERE table_name = 'k2' AND column_default IS NOT NULL"
        ),
        vec!["a"]
    );
    e.execute("INSERT INTO k2 (id, b) VALUES (1, 5)").unwrap();
    assert_eq!(rows(&mut e, "SELECT a FROM k2"), vec!["dd"]);
    // Still no CHECK.
    e.execute("INSERT INTO k2 (id, b) VALUES (2, -5)").unwrap();
    assert_eq!(rows(&mut e, "SELECT count(*) FROM k2"), vec!["2"]);
}

/// `INCLUDING CONSTRAINTS` brings the CHECK, and a LIKE can sit beside
/// explicit columns — which come first, as written.
#[test]
fn round531_including_constraints_and_written_order() {
    let mut e = engine();
    e.execute("CREATE TABLE k3 (x INT, LIKE src INCLUDING CONSTRAINTS)")
        .unwrap();
    assert_eq!(cols(&mut e, "k3"), vec!["x", "id", "a", "b"]);
    assert!(
        e.execute("INSERT INTO k3 VALUES (0, 1, 'x', -5)").is_err(),
        "the copied CHECK should reject b = -5"
    );
    e.execute("INSERT INTO k3 VALUES (0, 1, 'x', 5)").unwrap();
    assert_eq!(rows(&mut e, "SELECT count(*) FROM k3"), vec!["1"]);
}

/// A generated column and an identity column, with and without their
/// INCLUDING.
#[test]
fn round531_generated_and_identity_need_their_option() {
    let mut e = engine();
    e.execute(
        "CREATE TABLE gsrc (id INT GENERATED BY DEFAULT AS IDENTITY, \
         b INT, c INT GENERATED ALWAYS AS (b * 2) STORED)",
    )
    .unwrap();
    e.execute("CREATE TABLE g1 (LIKE gsrc)").unwrap();
    e.execute("CREATE TABLE g2 (LIKE gsrc INCLUDING ALL)")
        .unwrap();
    // Bare: `c` is a plain column, so it takes a written value.
    e.execute("INSERT INTO g1 (id, b, c) VALUES (1, 5, 99)")
        .unwrap();
    assert_eq!(rows(&mut e, "SELECT c FROM g1"), vec!["99"]);
    // With ALL: `c` is generated, and computes.
    e.execute("INSERT INTO g2 (b) VALUES (5)").unwrap();
    assert_eq!(rows(&mut e, "SELECT c FROM g2"), vec!["10"]);
}

/// v7.39 (round 621) — INCLUDING INDEXES copies them now. This pin used to
/// assert the refusal (round 531's honest stand-in: refusing beats a table
/// that reports the right columns and none of the indexes). The refusal took
/// `INCLUDING ALL` down with it, which is what schema tools write, so the
/// restore stopped instead. The copies are rebuilt through the ordinary
/// CREATE INDEX path and named by the auto-namer against the NEW table.
#[test]
fn round621_including_indexes_copies_them() {
    let mut e = engine();
    e.execute("CREATE INDEX src_b ON src(b)").unwrap();
    e.execute("CREATE UNIQUE INDEX src_a ON src(a)").unwrap();
    e.execute("CREATE TABLE k4 (LIKE src INCLUDING INDEXES)")
        .unwrap();
    assert_eq!(
        rows(
            &mut e,
            "SELECT count(*) FROM pg_indexes WHERE tablename = 'k4'"
        ),
        vec!["3"],
        "the PK's index, the plain one and the unique one all copy"
    );
    // The unique one still enforces on the copy.
    e.execute("INSERT INTO k4 (id, a, b) VALUES (1, 'x', 1)")
        .unwrap();
    assert!(
        e.execute("INSERT INTO k4 (id, a, b) VALUES (2, 'x', 2)")
            .is_err(),
        "the copied UNIQUE index is a real constraint, not a name"
    );
    // And the source keeps its own names — no collision between the two.
    assert_eq!(
        rows(
            &mut e,
            "SELECT count(*) FROM pg_indexes WHERE tablename = 'src'"
        ),
        vec!["3"]
    );
}
