//! v7.39 (round 621) — `by` could not be used as a name anywhere.
//!
//! `CREATE TABLE t (by BYTEA)` was a syntax error, and so was every read,
//! write, index and alias of such a column. `pg_get_keywords()` classes `by`
//! as `U` — unreserved — so PG takes it as an ordinary identifier; SPG lexed
//! it into a dedicated `Token::By` for the three clauses that own the word.
//!
//! Of the seven two-letter keywords the lexer knew, this is the only one PG
//! leaves unreserved: `as`, `in`, `on`, `or` and `to` are reserved and `is` is
//! `T`. So the fix is exactly one word wide, and the pins below check the
//! other six stay keywords.
//!
//! The first cut added `by` to the unreserved-identifier table, which is where
//! `release`, `savepoint` and the rest live, and it was not enough: identifier
//! positions that match the token shape directly — an index's column list, a
//! table alias — never consult that table, so `CREATE INDEX … ON t(by)` and
//! `FROM t AS by` still failed. Patching those two would have left every other
//! such position broken, so the word is simply no longer lexed as a keyword
//! and the clauses that need it (GROUP BY, ORDER BY, PARTITION BY, OWNED BY,
//! GENERATED BY DEFAULT) recognise it as the identifier it is.
//!
//! All twelve shapes were checked against live PG18 and match byte for byte.

use spg_engine::{Engine, QueryResult};

fn vals(e: &mut Engine, sql: &str) -> Vec<String> {
    match e.execute(sql).unwrap_or_else(|err| panic!("{sql}: {err}")) {
        QueryResult::Rows { rows, .. } => rows
            .iter()
            .map(|r| {
                r.values
                    .iter()
                    .map(spg_engine::eval::value_to_text)
                    .collect::<Vec<_>>()
                    .join("|")
            })
            .collect(),
        other => panic!("{sql}: {other:?}"),
    }
}

fn seed() -> Engine {
    let mut e = Engine::new();
    e.execute("CREATE TABLE r1 (by BYTEA, id INT)").unwrap();
    e.execute(r"INSERT INTO r1 VALUES ('\x01', 1)").unwrap();
    e
}

/// Every position a name can stand in.
#[test]
fn round621_by_is_a_column_name() {
    let mut e = seed();
    assert_eq!(vals(&mut e, "SELECT by, id FROM r1"), vec![r"\x01|1"]);
    assert_eq!(
        vals(&mut e, "SELECT r1.by FROM r1"),
        vec![r"\x01"],
        "qualified"
    );
    assert_eq!(
        vals(&mut e, "SELECT by FROM r1 WHERE by IS NOT NULL"),
        vec![r"\x01"],
        "in a predicate"
    );
    assert_eq!(
        vals(&mut e, "SELECT by AS b FROM r1 ORDER BY by"),
        vec![r"\x01"],
        "aliased, and ordered by — where the clause keyword and the column \
         name are the same word, twice in a row"
    );
    assert_eq!(
        vals(&mut e, "SELECT count(*) FROM r1 GROUP BY by"),
        vec!["1"],
        "and grouped by"
    );
    e.execute(r"UPDATE r1 SET by = '\x02'").unwrap();
    assert_eq!(vals(&mut e, "SELECT by FROM r1"), vec![r"\x02"], "written");
    e.execute("ALTER TABLE r1 ADD COLUMN by2 INT").unwrap();
    assert_eq!(vals(&mut e, "SELECT by2 FROM r1"), vec!["NULL"]);
}

/// The two positions the table-based first cut did not reach.
#[test]
fn round621_the_positions_a_keyword_table_does_not_cover() {
    let mut e = seed();
    e.execute("CREATE INDEX r1by ON r1(by)")
        .expect("an index's column list matches the token shape directly");
    assert_eq!(
        vals(&mut e, r"SELECT count(*) FROM r1 WHERE by = '\x01'"),
        vec!["1"]
    );
    assert_eq!(
        vals(&mut e, "SELECT by FROM r1 AS by"),
        vec![r"\x01"],
        "a table alias, likewise"
    );
    assert_eq!(
        vals(
            &mut e,
            "SELECT string_agg(by::TEXT, ',' ORDER BY id) FROM r1"
        ),
        vec![r"\x01"],
        "and inside an ordered aggregate, where BY appears as both"
    );
}

/// The clauses that own the word still own it.
#[test]
fn round621_the_clauses_still_work() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE k (a INT, b INT)").unwrap();
    e.execute("INSERT INTO k VALUES (1,10),(1,20),(2,30)")
        .unwrap();
    assert_eq!(
        vals(&mut e, "SELECT a, count(*) FROM k GROUP BY a ORDER BY a"),
        vec!["1|2", "2|1"]
    );
    assert_eq!(
        vals(
            &mut e,
            "SELECT sum(b) OVER (PARTITION BY a ORDER BY b) FROM k ORDER BY 1"
        ),
        vec!["10", "30", "30"]
    );
    assert_eq!(
        vals(&mut e, "SELECT a FROM k ORDER BY a DESC, b ASC LIMIT 1"),
        vec!["2"]
    );
}

/// The six two-letter keywords that are NOT unreserved stay keywords.
#[test]
fn round621_the_other_two_letter_keywords_are_untouched() {
    let mut e = Engine::new();
    for word in ["as", "in", "on", "or", "to", "is"] {
        assert!(
            e.execute(&format!("CREATE TABLE bad_{word} ({word} INT)"))
                .is_err(),
            "`{word}` is reserved in PG and must stay a keyword here"
        );
    }
    // And they still parse as the keywords they are.
    e.execute("CREATE TABLE q (x INT)").unwrap();
    e.execute("INSERT INTO q VALUES (1),(2)").unwrap();
    assert_eq!(
        vals(
            &mut e,
            "SELECT x AS y FROM q WHERE x IN (1) AND x IS NOT NULL"
        ),
        vec!["1"]
    );
}
