//! 9.0.0 — `GENERATED BY DEFAULT AS IDENTITY` was not an identity
//! column to the catalogs, and the three ALTER forms were no-ops.
//!
//! The column schema recorded one bool, `identity_always`, which
//! answered "is this the ALWAYS one" and could not tell `BY DEFAULT`
//! from a plain `serial`: both read `false`. So
//! `information_schema.columns` reported `is_identity NO` and
//! `pg_attribute.attidentity` an empty string — PostgreSQL 18.6's
//! answer for "not an identity column at all" — for a column that is
//! one. It is a three-state now (`None` with `auto_increment` is
//! `serial`), persisted in its own FILE_VERSION 102 appendix beside the
//! 8.0.3 one so an older image still reads.
//!
//! Measured on PG 18.6, the ALTER sequence this closes:
//!
//! ```text
//!   ADD GENERATED BY DEFAULT AS IDENTITY   was a no-op (is_identity NO)
//!   SET GENERATED ALWAYS                   was a no-op
//!   ADD … on a NULLABLE column             accepted; PG refuses
//!   ADD … twice                            accepted; PG refuses
//!   DROP IDENTITY IF EXISTS on a plain col silent; PG says so
//! ```

use spg_engine::{Engine, QueryResult};

fn col(e: &mut Engine, sql: &str) -> Vec<String> {
    let QueryResult::Rows { rows, .. } = e
        .execute(sql)
        .unwrap_or_else(|err| panic!("{sql}: {err:?}"))
    else {
        panic!("expected rows for {sql}");
    };
    rows.into_iter()
        .map(|r| spg_engine::eval::value_to_text(r.values.first().expect("one column")))
        .collect()
}

fn err(e: &mut Engine, sql: &str) -> String {
    format!("{}", e.execute(sql).unwrap_err())
}

fn shape(e: &mut Engine, table: &str) -> String {
    col(
        e,
        &format!(
            "SELECT is_identity||' '||coalesce(identity_generation,'-') \
             FROM information_schema.columns \
             WHERE table_name='{table}' AND column_name='id'"
        ),
    )
    .remove(0)
}

#[test]
fn both_identity_flavours_name_themselves() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE i1 (id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    e.execute("CREATE TABLE i2 (id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    assert_eq!(shape(&mut e, "i1"), "YES BY DEFAULT");
    assert_eq!(shape(&mut e, "i2"), "YES ALWAYS");
    assert_eq!(
        col(
            &mut e,
            "SELECT attidentity::text FROM pg_attribute \
             WHERE attrelid='i1'::regclass AND attname='id'"
        ),
        vec!["d".to_string()]
    );
    assert_eq!(
        col(
            &mut e,
            "SELECT attidentity::text FROM pg_attribute \
             WHERE attrelid='i2'::regclass AND attname='id'"
        ),
        vec!["a".to_string()]
    );
    // A plain serial is NOT an identity column on PostgreSQL, and the
    // three-state has to keep saying so.
    e.execute("CREATE TABLE i0 (id serial, v text)").unwrap();
    assert_eq!(shape(&mut e, "i0"), "NO -");
}

#[test]
fn add_and_set_generated_take_effect() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE i3 (id int NOT NULL, v text)")
        .unwrap();
    e.execute("ALTER TABLE i3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
        .unwrap();
    assert_eq!(shape(&mut e, "i3"), "YES BY DEFAULT");
    e.execute("ALTER TABLE i3 ALTER COLUMN id SET GENERATED ALWAYS")
        .unwrap();
    assert_eq!(shape(&mut e, "i3"), "YES ALWAYS");
    e.execute("ALTER TABLE i3 ALTER COLUMN id DROP IDENTITY")
        .unwrap();
    assert_eq!(shape(&mut e, "i3"), "NO -");
}

#[test]
fn pgs_two_refusals_and_its_notice() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE i4 (id int, v text)").unwrap();
    // A NULLABLE column cannot become an identity column.
    assert!(
        err(
            &mut e,
            "ALTER TABLE i4 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY"
        )
        .contains("must be declared NOT NULL before identity can be added"),
        "{}",
        err(
            &mut e,
            "ALTER TABLE i4 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY"
        )
    );
    // DROP IDENTITY IF EXISTS on a plain column says so.
    e.execute("ALTER TABLE i4 ALTER COLUMN id DROP IDENTITY IF EXISTS")
        .unwrap();
    let notices: Vec<String> = e.take_notices().into_iter().map(|n| n.message).collect();
    assert_eq!(
        notices,
        vec!["column \"id\" of relation \"i4\" is not an identity column, skipping".to_string()]
    );
    // And without IF EXISTS it is an error.
    assert!(
        err(&mut e, "ALTER TABLE i4 ALTER COLUMN id DROP IDENTITY")
            .contains("is not an identity column"),
        "{}",
        err(&mut e, "ALTER TABLE i4 ALTER COLUMN id DROP IDENTITY")
    );
    // A second ADD is refused.
    e.execute("CREATE TABLE i5 (id int NOT NULL, v text)")
        .unwrap();
    e.execute("ALTER TABLE i5 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY")
        .unwrap();
    assert!(
        err(
            &mut e,
            "ALTER TABLE i5 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY"
        )
        .contains("is already an identity column"),
        "{}",
        err(
            &mut e,
            "ALTER TABLE i5 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY"
        )
    );
}

#[test]
fn the_always_flavour_still_refuses_an_explicit_value() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE i6 (id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    assert!(!err(&mut e, "INSERT INTO i6 VALUES (7,'a')").is_empty());
    // BY DEFAULT takes one.
    e.execute("CREATE TABLE i7 (id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO i7 VALUES (7,'a')").unwrap();
    assert_eq!(col(&mut e, "SELECT id FROM i7"), vec!["7".to_string()]);
}
