//! v7.38 (read01) — `GENERATED ALWAYS AS IDENTITY` vs `GENERATED BY DEFAULT
//! AS IDENTITY`, and the `OVERRIDING { SYSTEM | USER } VALUE` clause.
//!
//! PG (verified live against PG18.4) rejects an explicit non-DEFAULT INSERT
//! value for an ALWAYS identity column ("cannot insert a non-DEFAULT value
//! into column …") unless the statement carries `OVERRIDING SYSTEM VALUE`; a
//! `DEFAULT` keyword or an omitted column is always fine. `OVERRIDING USER
//! VALUE` ignores an explicit value on an identity column and generates from
//! the sequence instead. A BY DEFAULT identity column accepts an explicit
//! value unmodified.
//!
//! NB: SPG mints identity values with a max+1 scan rather than an independent
//! sequence object, so a generated value that follows a *larger* explicit
//! value diverges from PG. These tests deliberately never assert a generated
//! value across that interaction — that pre-existing simplification is out of
//! this feature's scope.

use spg_engine::{Engine, QueryResult};

fn col(e: &mut Engine, sql: &str) -> Vec<String> {
    match e
        .execute(sql)
        .unwrap_or_else(|err| panic!("{sql}: {err:?}"))
    {
        QueryResult::Rows { rows, .. } => rows
            .iter()
            .map(|r| match &r.values[0] {
                spg_storage::Value::Text(s) => s.to_string(),
                other => format!("{other:?}"),
            })
            .collect(),
        other => panic!("{sql}: expected Rows, got {other:?}"),
    }
}

#[test]
fn always_identity_generates_when_omitted() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO t(v) VALUES ('a'),('b')").unwrap();
    assert_eq!(
        col(&mut e, "SELECT (id||':'||v)::text FROM t ORDER BY id"),
        vec!["1:a", "2:b"]
    );
}

#[test]
fn always_identity_rejects_explicit_value() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    // Explicit value with a column list → rejected.
    assert!(e.execute("INSERT INTO t(id,v) VALUES (100,'x')").is_err());
    // Explicit value positionally (no column list) → also rejected.
    assert!(e.execute("INSERT INTO t VALUES (100,'x')").is_err());
    // Mixed multi-row: one row supplies an explicit value → whole stmt rejected.
    assert!(
        e.execute("INSERT INTO t(id,v) VALUES (DEFAULT,'a'),(5,'b')")
            .is_err()
    );
    // Nothing landed.
    assert_eq!(col(&mut e, "SELECT count(*)::text FROM t"), vec!["0"]);
}

#[test]
fn always_identity_accepts_default_keyword() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO t(id,v) VALUES (DEFAULT,'a')")
        .unwrap();
    e.execute("INSERT INTO t VALUES (DEFAULT,'b')").unwrap();
    assert_eq!(
        col(&mut e, "SELECT (id||':'||v)::text FROM t ORDER BY id"),
        vec!["1:a", "2:b"]
    );
}

#[test]
fn overriding_system_value_uses_explicit_on_always() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO t(id,v) OVERRIDING SYSTEM VALUE VALUES (100,'y')")
        .unwrap();
    assert_eq!(
        col(&mut e, "SELECT (id||':'||v)::text FROM t"),
        vec!["100:y"]
    );
}

#[test]
fn overriding_user_value_ignores_explicit_on_always() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED ALWAYS AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO t(v) VALUES ('a')").unwrap();
    // USER override: the supplied 500 is discarded, the sequence generates 2.
    e.execute("INSERT INTO t(id,v) OVERRIDING USER VALUE VALUES (500,'z')")
        .unwrap();
    assert_eq!(
        col(&mut e, "SELECT (id||':'||v)::text FROM t ORDER BY id"),
        vec!["1:a", "2:z"]
    );
}

#[test]
fn by_default_identity_accepts_explicit_value() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    // Generate first, then an explicit larger value — both land as-is.
    e.execute("INSERT INTO t(v) VALUES ('b')").unwrap();
    e.execute("INSERT INTO t(id,v) VALUES (7,'a')").unwrap();
    assert_eq!(
        col(&mut e, "SELECT (id||':'||v)::text FROM t ORDER BY id"),
        vec!["1:b", "7:a"]
    );
}

#[test]
fn overriding_user_value_ignores_explicit_on_by_default() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE t(id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO t(v) VALUES ('a')").unwrap();
    // USER override on a BY DEFAULT column also discards the explicit 9 → 2.
    e.execute("INSERT INTO t(id,v) OVERRIDING USER VALUE VALUES (9,'c')")
        .unwrap();
    assert_eq!(
        col(&mut e, "SELECT (id||':'||v)::text FROM t ORDER BY id"),
        vec!["1:a", "2:c"]
    );
}
