//! v7.39 (round 220) — identity / sequence / domain differential fixes.
//! Live-PG18.4 differential (2026-07-19) found three gaps, all fixed:
//!   1. `ALTER TABLE … ALTER COLUMN … RESTART [WITH n]` was unparsed
//!      (pg_dump / migration tools emit it). SPG records a next-value
//!      floor over its max+1 identity allocation: a dump-restore RESTART
//!      lands exactly on n; a backward RESTART is safely ignored (no
//!      duplicate-key landmine, unlike PG). Persisted (FILE_VERSION 73).
//!   2. A CYCLE-less sequence past its bound was classed as a Corrupt
//!      storage error ("corrupt on-disk format: …"); PG's 2200H wording
//!      is `nextval: reached maximum value of sequence "s" (n)`.
//!   3. Domain violations through the table-INSERT path used SPG-internal
//!      wording; PG's is `value for domain d violates check constraint
//!      "d_check"` and `domain d does not allow null values`.

use spg_engine::{Engine, QueryResult};

fn one(e: &mut Engine, sql: &str) -> String {
    match e.execute(sql).unwrap() {
        QueryResult::Rows { rows, .. } => rows
            .first()
            .map(|r| format!("{:?}", r.values[0]))
            .unwrap_or_default(),
        other => panic!("{other:?}"),
    }
}

#[test]
fn restart_with_lands_on_the_floor() {
    let mut e = Engine::new();
    e.execute("CREATE TABLE idd (id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO idd (v) VALUES ('a')").unwrap();
    e.execute("ALTER TABLE idd ALTER COLUMN id RESTART WITH 100")
        .unwrap();
    e.execute("INSERT INTO idd (v) VALUES ('d')").unwrap();
    assert_eq!(
        one(&mut e, "SELECT id FROM idd WHERE v = 'd'"),
        "Int(100)"
    );
    // …and the allocation continues from there.
    e.execute("INSERT INTO idd (v) VALUES ('e')").unwrap();
    assert_eq!(
        one(&mut e, "SELECT id FROM idd WHERE v = 'e'"),
        "Int(101)"
    );
}

#[test]
fn restart_floor_survives_catalog_round_trip() {
    // The floor persists (FILE_VERSION 73 appendix): a restart between the
    // ALTER and the next INSERT must not lose it.
    use spg_storage::Catalog;
    let mut e = Engine::new();
    e.execute("CREATE TABLE idd (id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO idd (v) VALUES ('a')").unwrap();
    e.execute("ALTER TABLE idd ALTER COLUMN id RESTART WITH 500")
        .unwrap();
    let bytes = e.catalog().serialize();
    let restored = Catalog::deserialize(&bytes).unwrap();
    let mut e2 = Engine::restore(restored);
    e2.execute("INSERT INTO idd (v) VALUES ('b')").unwrap();
    assert_eq!(
        one(&mut e2, "SELECT id FROM idd WHERE v = 'b'"),
        "Int(500)"
    );
}

#[test]
fn bare_restart_is_backward_and_safely_ignored() {
    // Bare RESTART = restart from 1; SPG's max+1 floor semantics make a
    // backward restart a no-op (safer than PG's duplicate-key landmine).
    let mut e = Engine::new();
    e.execute("CREATE TABLE idd (id int GENERATED BY DEFAULT AS IDENTITY, v text)")
        .unwrap();
    e.execute("INSERT INTO idd (v) VALUES ('a'),('b')").unwrap();
    e.execute("ALTER TABLE idd ALTER COLUMN id RESTART").unwrap();
    e.execute("INSERT INTO idd (v) VALUES ('c')").unwrap();
    assert_eq!(one(&mut e, "SELECT id FROM idd WHERE v = 'c'"), "Int(3)");
}

#[test]
fn sequence_limit_message_matches_pg() {
    let mut e = Engine::new();
    e.execute("CREATE SEQUENCE ncyc MAXVALUE 2").unwrap();
    e.execute("SELECT nextval('ncyc')").unwrap();
    e.execute("SELECT nextval('ncyc')").unwrap();
    let err = e.execute("SELECT nextval('ncyc')").unwrap_err().to_string();
    assert!(
        err.contains("nextval: reached maximum value of sequence \"ncyc\" (2)"),
        "{err}"
    );
    assert!(!err.contains("corrupt"), "must not class as Corrupt: {err}");
}

#[test]
fn domain_violation_messages_match_pg() {
    let mut e = Engine::new();
    e.execute("CREATE DOMAIN posint AS int CHECK (VALUE > 0) NOT NULL")
        .unwrap();
    e.execute("CREATE TABLE dt (x posint)").unwrap();
    e.execute("INSERT INTO dt VALUES (5)").unwrap();
    let err = e.execute("INSERT INTO dt VALUES (-1)").unwrap_err().to_string();
    assert!(
        err.contains("value for domain posint violates check constraint \"posint_check\""),
        "check wording: {err}"
    );
    let err = e
        .execute("INSERT INTO dt VALUES (NULL)")
        .unwrap_err()
        .to_string();
    assert!(
        err.contains("domain posint does not allow null values"),
        "null wording: {err}"
    );
    // Plain column NOT NULL keeps the column-level 23502 wording.
    e.execute("CREATE TABLE pt (y int NOT NULL)").unwrap();
    let err = e
        .execute("INSERT INTO pt VALUES (NULL)")
        .unwrap_err()
        .to_string();
    assert!(
        err.contains("null value in column \"y\""),
        "column wording unchanged: {err}"
    );
}
