-- MySQL's three-valued logic and its own NULL-safe operator.
SELECT 'T01', NULL = NULL, NULL <> NULL, NULL <=> NULL, 1 <=> 1;
SELECT 'T02', ISNULL(NULL), ISNULL(0), COALESCE(NULL,NULL,3);
SELECT 'T03', IFNULL(NULL,'d'), IFNULL('v','d'), NULLIF(1,1), NULLIF(1,2);
SELECT 'T04', NULL AND 0, NULL AND 1, NULL OR 1, NULL OR 0;
SELECT 'T05', NOT NULL, NULL XOR 1, 1 XOR 1;
SELECT 'T06', IF(NULL,'y','n'), CASE WHEN NULL THEN 'y' ELSE 'n' END;
SELECT 'T07', name, amt IS NULL, note IS NOT NULL FROM mc_t ORDER BY id;
SELECT 'T08', COUNT(amt), COUNT(*), AVG(amt) FROM mc_t;
SELECT 'T09', GREATEST(1,NULL,2), LEAST(1,NULL,2);
SELECT 'T10', CONCAT('a',NULL,'b'), CONCAT_WS('-','a',NULL,'b');
SELECT 'T11', 1 IN (1,NULL), 2 IN (1,NULL), 2 NOT IN (1,NULL);
SELECT 'T12', (SELECT amt FROM mc_t WHERE id=99) IS NULL;
